### ISSUE TITLE
workshop: Docker hands-on, Nov 9-10, 2015

### ISSUE THREAD

**Issue by ctb** [ged-lab/dib-training#1]
Please 'subscribe' (lower right) if you are interested in this workshop, which will be on gaining some hands-on experience with Docker.

**Comment by jessicalumian** [comment]
Here is the information page: http://dib-training.readthedocs.org/en/pub/2015-11-09-docker.html

Register here: https://www.eventbrite.com/e/docker-hands-on-tickets-19064340957
