### ISSUE TITLE
Agenda for iPlant Collaborative workshop

### ISSUE THREAD

**Issue by ctb** [ged-lab/dib-training#11]
Agenda for #3. cc @mwvaughn, @JasonJWilliamsNY

**Comment by JasonJWilliamsNY** [comment]
Hi Everyone, here is the first thing that came to mind. I had the idea that after day one, we could then allow participants to choose the path that is most interesting to them. Of course we also have to thing about how much staffing and help we need. There are a fair number of UC Davis users so as soon as we have an agenda, we should get the word out to them. 

<h2>Day 1</h2>

<h4>Intro iPlant</h4>
- Data upload and sharing (no cmd line)
- Analysis in Discovery Environment
- RNA-Seq demo experiment
- Intro to Atmosphere

<h2>Day 2</h2>

**Chose One**

<h4>iPlant Intermediate</h4>
- Working effectively with iRODS and iCommands
- Using HPC apps (MAKER-P from upload 2 visualization with JBrowse) DE/Atmosphere
- RNA-Seq w/Kallisto - no material here, but we could probably do in Atm and get H. Pimentel to do a demo?
- RNA-Seq visualization with cummeRbund

<h4>Data Carpentry with iPlant</h4>
- Day 1 of DC NGS materials hosted by Atmosphere

<h2>Day 3</h2>

**Chose One**

<h4>iPlant Advanced (Hackathon)</h4>
- Intro to Agave
- Auth/App management
- Job management 
- Docker

<h4>Data Carpentry with iPlant</h4>
- Day 2 of DC NGS materials hosted by Atmosphere

**Comment by ctb** [comment]
I like all of the options! How many rooms are you thinking of? I still need to reserve them :).

**Comment by JasonJWilliamsNY** [comment]
I am going to try to pin down folks, but I think if we have two rooms that will be great. Also need to figure out what are the high-value pieces because we do have equipment to record and/or stream

**Comment by JasonJWilliamsNY** [comment]
@niravmerchant is working on flights for day 2 and 3

**Comment by JasonJWilliamsNY** [comment]
I am confirming iPlant people this week if at all possible. I think we need to have a conference call next week with UC Davis and Oregon folks next week;

**Comment by JasonJWilliamsNY** [comment]
@mwvaughn and @johnfonner confirmed on board. 
@Kapeel on board

**Comment by RareSeas** [comment]
Hi - I just filled out the doodle poll about the conference call.  I am interested in coming to assist in instruction with the hopes of setting up similar training at Oregon State.

**Comment by danfulop** [comment]
I can join the conference call and will have some time to assist with instruction. I am particularly interested in attending (as either an helper-instructor or a regular attendee) the kallisto demo and/or the MAKER one.

**Comment by ctb** [comment]
It looks like the rooms will be as follows; waiting for final confirmation, but I have informal assurances :).

Monday, 9/21 - 1010 Valley (9/21) - 80 people, good big lecture hall format - Introduction to iPlant

Tues & Wed, 9/22-9/23 - 1043 Valley - 45 people, tiered wide format - Data Carpentry

Tues, 9/22 - 1041 Valley - 45 people, tiered wide format - iPlant Intermediate

Wed 9/23 - 2020 Valley (9/23) - 60 people, flat format, good for working in groups - Hackathon

@JasonJWilliamsNY on reflection I think I should do the eventbrite thing so that I can manage 50% VetMed & the waiting lists.  Sound OK?

**Comment by niravmerchant** [comment]
Hi Folks,
Did we have ideas/short list of topic suitable for hackathon ?
Sorry I missed yesterdays planning meeting, in case it was covered
Regards,
Nirav

**Comment by RareSeas** [comment]
This is what is currently on the agenda:

iPlant Advanced (Hackathon)
-   Intro to Agave
-   Auth/App management
-   Job management
-   Docker

**Comment by mwvaughn** [comment]
This is a potentially very fruitful set of topics - high on my agenda is to make sure that attendees learn that you can be _productive_ using these lower-level interfaces to iPlant and its underlying resources. This is a subtle change in messaging from before, which has been that the service layer @ iPlant was what one used to build web applications for end users.

**Comment by ctb** [comment]
On Wed, Aug 26, 2015 at 06:27:20AM -0700, Matthew Vaughn wrote:

> This is a potentially very fruitful set of topics - high on my agenda is to make sure that attendees learn that you can be _productive_ using these lower-level interfaces to iPlant and its underlying resources. This is a subtle change in messaging from before, which has been that the service layer @ iPlant was what one used to build web applications for end users.

+1

**Comment by ctb** [comment]
Hi all, the rooms have now been approved, huzzah!  I have them reserved from 8am to 6pm, but I'd like to suggest starting official activities at 9:15am and ending them by 4:45pm (we can say 9 and 5 but plan for 9:15 and 4:45 to allow for late arrivals etc).  Sound OK?

@JasonJWilliamsNY shall I set up eventbrite pages?

**Comment by ctb** [comment]
http://dib-training.readthedocs.org/en/pub/2015-09-iplant.html
- [x] establish eventbrite pages for four separate workshops;
- [x] write announcements;
- [ ] announce to SVM, dib-training and friends on Monday morning;
- [ ] send more widely on Tuesday morning;

cc @jessicamizzi

**Comment by ctb** [comment]
Eventbrite links:

intro: https://www.eventbrite.com/e/introduction-to-iplant-registration-18396355996

DC: https://www.eventbrite.com/e/doing-genomics-on-iplant-a-data-carpentry-workshop-registration-18396466326

Intermediate: https://www.eventbrite.com/e/iplant-for-advanced-users-registration-18396590698

If someone could check over the links for me before I post it all live, I'd appreciate it! Note that half the tickets are invisible; you need a special code to see them.

**Comment by ctb** [comment]
Note that I didn't put in tickets for the hackathon. Should I? I don't know how formal that's going to be.
