### ISSUE TITLE
workshop: iPlant Collaborative hands-on, Sep 21-23, 2015.

### ISSUE THREAD

**Issue by ctb** [ged-lab/dib-training#3]
Please 'subscribe' (lower right) if you are interested in this workshop, which will be on gaining some hands-on experience with iPlant, at both beginner and advanced levels.

**Comment by ctb** [comment]
We may be moving this to Sep 21/22/23; will update when I know.

**Comment by JasonJWilliamsNY** [comment]
I am a go for any event the week of Sept: 21st 
- Should be noted that YomKippur is 22nd - will this impact us on the west coast?
- Nirav will try (if at all possible to come)
- Matt Vaughn and if possible one other TACC person is on board. 

Do Matt and Nirav collaborators here so they can work on this issue?
Do we need to open a draft agenda as a new issue?

**Comment by ctb** [comment]
Great!

I expect the biggest attendance to be on the most general day, so that would be Monday the 21st; 22nd could be reserved for more technical/advanced stuff.  So let's plan on 21/22/23.

We can do a draft agenda here or as a new issue, up to you.

I don't have Matt or Nirav's github IDs, send 'em to me and I'll invite.

**Comment by JasonJWilliamsNY** [comment]
Matt: mwvaughn
Nirav: Will ping - but he may be out on vacation for a few days. 

If you create a new issue, I will post a draft agenda there. 
I think the plan was also to use some of the new Data Carpentry materials as well...  so we can work a bit to tie that, plus API stuff so that we work our way up to the more technical items.

**Comment by tracykteal** [comment]
I think the genomics Data Carpentry materials would be good here. There's also some work on an API lesson so if we want to do API things, that lesson might be a good place to start. 

Looks like the agenda issue is https://github.com/dib-lab/dib-training/issues/11
